### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by betelqeyza** [CaNNiC2/rbe-zombie-meat-4.3#6]
can u remove glow in nenemis mode? because im playing with 10 fps. :trollface:

**Comment by iCHOPPERi** [comment]
No.

**Comment by betelqeyza** [comment]
> No.

amogus

**Comment by RBEsLayeR** [comment]
> can u remove glow in nenemis mode? because im playing with 10 fps. :trollface:

NO.
Get a new haircuttttttttttttttt
